//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace WcfConnectionClosed
{
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class Table
    {
        [DataMember]
        public int Id { get; set; }

        [DataMember]
        public string Field1 { get; set; }

        [DataMember]
        public string Field2 { get; set; }
    }
}
